config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root "static_pages#home"
  get "/contact",to: "static_pages#contact"
  # get "/home",   to: "static_pages#home"
  get "/help" ,to:"static_pages#help"
  get "/about" ,to: "static_pages#about"

  get "/signup" , to:"users#new"
  get "/users" ,to: "users#index"
  #get "/users/new", to:"users#new"
  get "/users/:id", to:"users#show"
  post "/users", to:"users#create"
  post "/signup", to:"users#create"
  get "/users/:id/edit" ,to: "users#edit"
  patch "/users/:id" ,to: "users#update"
  delete "/users/delete" , to: "users#destroy"

  get "/login" , to: "sessions#new"
  post "/login" , to: "sessions#create"
  delete "/logout" , to: "sessions#destroy"
resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save {self.email = email.downcase}
  validates :name , presence: true , length: {minimum: 3}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true , uniqueness: true , format: {with: VALID_EMAIL_REGEX}

  has_secure_password
  validates :password, length: { minimum: 8 } , presence: true, allow_nil: true
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  #Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token =User.new_token
    update_attribute( :remember_digest, User.digest(remember_token))
  end
 # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
   def forget
     update_attribute(:remember_digest, nil)
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include UsersHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 before_action :check , only:[:new , :create]
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1'? remember(user) : forget(user)
      flash[:success] = "Xin Chao #{current_user.name} "
      redirect_to "/users/#{user.id}"
    else
      flash[:danger] = "Oops!! Please Try Again"
      render "new"
    end
  end

  def destroy
    log_out
    flash[:info] = "See You!"
    redirect_to root_path
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end

  def help

  end

  def about

  end

  def contact

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate, only: [ :edit, :update, :destroy]
before_action :correct_user, only: [:edit, :update]
before_action :check , only:[:new ,:create]
before_action :verify_admin? , only: [:destroy]


  def index
    @users = User.paginate(page: params[:page], per_page: 20)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new (user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome !"
      redirect_to "/users/#{@user.id}"
    else
      render :new
    end
  end
  def show
    #byebug
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]

  end

  def update
    @user = User.find params[:id]
      if @user.update! user_params
        flash[:success] = "Profile Updated!!"
        redirect_to "/users/#{@user.id}"
      else
        render :edit
      end

  end

  def destroy_login
    log_out
    redirect_to root_url
  end

  def destroy
    #byebug
    @user.destroy
    #@user =User.find(params[:id]).destroy
    flash[:success] = "User destroyed!"
    redirect_to "/users"
  end

  private

  def user_params
    params.require(:user).permit(:name , :email, :password, :password_confirmation)
  end

  def authenticate
    return if logged_in?
    flash[:danger] = "You do not Permission!!"
    redirect_to root_url
  end

  def correct_user
    @user = User.find(params[:id])
    return if @user == current_user
    flash[:warning] = "NOT Permission!!"
    redirect_to root_url
  end

  def verify_admin?
    @user = User.find(params[:id])
    return if current_user.admin?
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    app_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      app_title
    else
      page_title + " | " + app_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
    #session[:user_name] = user.name
  end

  def logged_in?
    current_user.present?
  end

  #Returns the current logged-in user (if any).
  def current_user
   if (user_id = session[:user_id])
    @current_user ||= User.find_by(id: user_id)
  elsif (user_id = cookies.signed[:user_id])
    user = User.find_by(id: user_id)
    if user && user.authenticate?(cookies[:remember_token])
      log_in user
      @current_user = user
    end
   end
  end

  def remember(user)
  user.remember
  cookies.permanent.signed[:user_id] = user.id
  cookies.permanent[:remember_token] = user.remember_token
  end

  def forget (user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)

  end

  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end

  def check
     return if !logged_in?
     flash[:warning] = "You should Log out to do access!"
     redirect_to root_url
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def full_title(page_title = '')
    app_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      app_title
    else
      page_title + " | " + app_title
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user ,option = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = option[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?size=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/users_hepler.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '/users' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             <%#= gravatar_for current_user %> <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", "/users/#{current_user.id}" %></li>
              <li><%= link_to "Settings", "/users/#{current_user.id}/edit" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
       <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <body>
    <h1>About</h1>
    <p>
      The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
      Tutorial</em></a> is a
      <a href="http://www.railstutorial.org/book">book</a> and
      <a href="http://screencasts.railstutorial.org/">screencast series</a>
      to teach web development with
      <a href="http://rubyonrails.org/">Ruby on Rails</a>.
      This is the sample application for the tutorial.
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>

app/views/static_pages/help.html.erb
<% provide(:title , "Help") %>
<!DOCTYPE html>
<html>
  <body>
    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/#help">Rails Tutorial help
      section</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<%provide(:title, "Home") %>
<!DOCTYPE html>
<html>
  <div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>
</html>

app/views/users/edit.html.erb
<% provide :title ,"Edit User" %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: {controller: "users" , action: :update}, html: {method: :patch}  do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Change Your Avatar</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate  %>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
    <%= link_to user.name, "/users/#{user.id}" %> ||
      <% if current_user.admin? && current_user != user && !user.admin? %>
      <%= link_to "Delete" , "/users/#{user.id}" ,method: :delete , data: {confirm: "Mày đã chắc chắn chưa ?"}  %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <br>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
      <br>
      <br>
      <label>Have you account?</label>
      <%= link_to "Click Me!", login_path %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
       <%= gravatar_for @user %>
       <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>